-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD'),PRODUCT_ID,USER_ID,SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM
(SELECT OFFLINE_SALE_ID, NULL AS USER_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE
FROM OFFLINE_SALE
UNION 
SELECT ONLINE_SALE_ID, USER_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE
FROM ONLINE_SALE)
WHERE TO_CHAR(SALES_DATE,'YYYY-MM')='2022-03'
GROUP BY SALES_DATE,PRODUCT_ID,USER_ID
ORDER BY SALES_DATE,PRODUCT_ID,USER_ID