-- 코드를 입력하세요
SELECT U.USER_ID,U.NICKNAME,U.CITY||' '|| U.STREET_ADDRESS1||' '|| STREET_ADDRESS2,
SUBSTR(U.TLNO,1,3)||'-'||SUBSTR(U.TLNO,4,4)||'-'||SUBSTR(U.TLNO,8)

FROM USED_GOODS_USER U
WHERE U.USER_ID IN (SELECT B.WRITER_ID AS W
FROM USED_GOODS_BOARD B
GROUP BY B.WRITER_ID
HAVING COUNT(*)>=3)
ORDER BY U.USER_ID DESC