-- 코드를 입력하세요
SELECT I.ANIMAL_ID,O.ANIMAL_TYPE,I.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID=O.ANIMAL_ID AND I.SEX_UPON_INTAKE like  '%Intact%' AND REGEXP_LIKE(O.SEX_UPON_OUTCOME ,'Spayed|Neutered')
ORDER BY I.ANIMAL_ID