-- 코드를 입력하세요
SELECT R.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(REVIEW_SCORE),2) AS RE
FROM REST_INFO R, REST_REVIEW RR
WHERE R.REST_ID=RR.REST_ID AND ADDRESS LIKE ('서울%')
GROUP BY R.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS
ORDER BY RE DESC,FAVORITES DESC