-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY') AS Y,TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS M,U.GENDER ,COUNT(DISTINCT S.USER_ID) AS C
FROM USER_INFO U,ONLINE_SALE S
WHERE U.USER_ID=S.USER_ID AND U.GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY'),TO_CHAR(SALES_DATE,'MM'),U.GENDER
ORDER BY Y,M,U.GENDER