-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(SALES_DATE,'YYYY')),TO_NUMBER(TO_CHAR(SALES_DATE,'MM')),COUNT(DISTINCT USER_ID)
,ROUND(COUNT(DISTINCT USER_ID)/
(
SELECT COUNT(DISTINCT USER_ID ) 
FROM USER_INFO
WHERE TO_CHAR(JOINED,'YYYY')='2021'
),1)
FROM ONLINE_SALE

WHERE USER_ID IN (SELECT DISTINCT USER_ID 
FROM USER_INFO
WHERE TO_CHAR(JOINED,'YYYY')='2021' )

GROUP BY TO_NUMBER(TO_CHAR(SALES_DATE,'YYYY')),TO_NUMBER(TO_CHAR(SALES_DATE,'MM'))
ORDER BY TO_NUMBER(TO_CHAR(SALES_DATE,'YYYY')),TO_NUMBER(TO_CHAR(SALES_DATE,'MM'))