-- 코드를 입력하세요
SELECT P.PRODUCT_ID,PRODUCT_NAME, SUM(AMOUNT*PRICE) AS S
FROM FOOD_PRODUCT P,FOOD_ORDER O
WHERE P.PRODUCT_ID=O.PRODUCT_ID AND  TO_CHAR(PRODUCE_DATE,'YYYY-MM')='2022-05'
GROUP BY P.PRODUCT_ID,PRODUCT_NAME
ORDER BY S DESC, P.PRODUCT_ID