-- 코드를 입력하세요
with TMP as (
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS CC,COUNT(*) AS C
FROM ANIMAL_OUTS T 
GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
ORDER BY TO_NUMBER(TO_CHAR(DATETIME,'HH24')))
SELECT P.EE
, CASE
WHEN (SELECT C FROM TMP WHERE P.EE=CC ) IS  NULL THEN 0
ELSE (SELECT C FROM TMP WHERE P.EE=CC )
    END
FROM 
(
SELECT LEVEL-1 AS EE
FROM DUAL 
CONNECT BY LEVEL<=24
) P