-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT, TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS E
FROM REST_REVIEW R ,MEMBER_PROFILE M
WHERE R.MEMBER_ID=M.MEMBER_ID AND M.MEMBER_ID=
(
SELECT MEMBER_ID
FROM(
SELECT MEMBER_ID, COUNT(*)
FROM REST_REVIEW R
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
    )
    WHERE ROWNUM<=1
)
ORDER BY E,REVIEW_TEXT